// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANcScdSD4pzz3UJI4NcCQiHXrQWL1bULI',
    appId: '1:104068320434:web:890c765f48b96d8eae4dab',
    messagingSenderId: '104068320434',
    projectId: 'bljrfirestore',
    authDomain: 'bljrfirestore.firebaseapp.com',
    storageBucket: 'bljrfirestore.appspot.com',
    measurementId: 'G-KBBCEM627E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4TtkpLOMu2f5y8DfUPjPBsXPGBEE2Z-k',
    appId: '1:104068320434:android:f40660e51a6243afae4dab',
    messagingSenderId: '104068320434',
    projectId: 'bljrfirestore',
    storageBucket: 'bljrfirestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR3h5VFnoaT__9_vJDXJXz4Y3qn7O1c5g',
    appId: '1:104068320434:ios:39ee9ff009874a6fae4dab',
    messagingSenderId: '104068320434',
    projectId: 'bljrfirestore',
    storageBucket: 'bljrfirestore.appspot.com',
    iosBundleId: 'com.example.belajarfirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR3h5VFnoaT__9_vJDXJXz4Y3qn7O1c5g',
    appId: '1:104068320434:ios:b0b97fb756e17619ae4dab',
    messagingSenderId: '104068320434',
    projectId: 'bljrfirestore',
    storageBucket: 'bljrfirestore.appspot.com',
    iosBundleId: 'com.example.belajarfirestore.RunnerTests',
  );
}
